project_id = "kywwyzoxegmehfdzqokx"

[functions.paypal]
verify_jwt = false

[functions.send-welcome-email]
verify_jwt = false

[functions.fetch-forum-economicus]
verify_jwt = false

[functions.send-chronicle-email]
verify_jwt = false

[functions.generate-chronicle]
verify_jwt = false

[functions.generate-caption]
verify_jwt = false

[functions.stripe-checkout]
verify_jwt = false

[functions.stripe-webhook]
verify_jwt = false

[functions.kofi-webhook]
verify_jwt = false

[functions.delete-user]
verify_jwt = false

[functions.subscribe-beehiiv]
verify_jwt = false
